name: railrl-env-4
channels:
- kne  # for pybox2d
- pytorch
- anaconda  # for mkl
dependencies:
  - flask=0.12.2=py35_0
  - joblib=0.9.4
  - mako=1.0.6=py35_0
  - matplotlib=2.2.2
  - mkl=2018.0.2  # Need to add explicit dependence for pytorch
  - numba=0.35.0=np111py35_0
  - numpy=1.11.3
  - path.py=10.3.1=py35_0
  - pybox2d=2.3.1post2=py35_0
  - python=3.5.2
  - python-dateutil=2.6.1=py35_0
  - pytorch=0.4.1
  - scipy=1.0.1
  - patchelf
  - pip:
    - cloudpickle==0.5.2
    - cached-property==1.3.1
    - gitpython==2.1.7
    - gtimer==1.0.0b5
    - gym[all]==0.10.5
    - moviepy==0.2.3.5
    - opencv-python==3.4.0.12
    - plotly==1.9.6
    - pygame==1.9.2
    - sk-video==1.1.10
    - torchvision==0.2.0
    - scikit-image
    # For doodad:
    - awscli==1.11.179
    - boto3==1.4.8
    - google-api-python-client
    - google-cloud-storage
    # I use these, but very rarely
    - dominate==2.3.1
    - ray==0.2.2
    # More optional ones:
    - ipdb==0.10.3
